import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
  BeforeInsert,
  BeforeUpdate,
} from 'typeorm';
import { TenantEntity } from './tenant.entity';

/**
 * Stores reusable component templates generated by the Copilot AI.
 * Each template captures the ComponentSchema JSON produced for a given
 * natural-language description so that it can be looked up and reused
 * without re-generating it from the model.
 */
@Entity('copilot_component_templates')
@Index(['tenantId', 'intent'])
@Index(['tenantId', 'createdAt'])
export class CopilotComponentTemplateEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'uuid', name: 'tenant_id' })
  tenantId: string;

  @ManyToOne(() => TenantEntity, { onDelete: 'CASCADE', nullable: false })
  @JoinColumn({ name: 'tenant_id' })
  tenant: TenantEntity;

  @Column({ type: 'varchar', length: 255, nullable: false })
  name: string;

  @Column({ type: 'text', nullable: false })
  description: string;

  @Column({ type: 'jsonb', nullable: false })
  schema: Record<string, unknown>;

  @Column({ type: 'varchar', length: 100, nullable: true })
  intent: string | null;

  @Column({ type: 'integer', name: 'use_count', default: 0, nullable: false })
  useCount: number;

  @CreateDateColumn({ type: 'timestamptz', name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz', name: 'updated_at' })
  updatedAt: Date;

  @BeforeInsert()
  setTimestampsOnInsert(): void {
    const now = new Date();
    this.createdAt = now;
    this.updatedAt = now;
  }

  @BeforeUpdate()
  setUpdatedAtOnUpdate(): void {
    this.updatedAt = new Date();
  }
}
